# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b527678f9db02532d792dda93b460f0f86a467d92a25e3a9c689357b5bf56fd25854c62414eaa61fe076014130ceada41b6fd559803fc70df330595ebfcf4acc

test:
  secret_key_base: 16249d498ec4211c0199b1340e3fe114eb2f2cc55a984f9c75d6121d06ccb34b99652cf8889e9e482a26706ac60b712dd408e82df39e53a960f5dac89d74d5eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
